// compare-react/src/components/Faq/Faq.js
import React, { Component } from 'react';
import './Faq.css';
import axios from 'axios';

class Faq extends Component {
    constructor(props){
      super(props);
      this.state = {
        faqs: []
      };
    }

    componentDidMount() {
      axios.get('http://jsonplaceholder.typicode.com/posts')
        .then(res => {
          const faqs = res.data.slice(0, 10);
          this.setState( { faqs });
        })
    }

    render() {
        return (
            <div>
              <div className="container">
                <section className="section">

                  <h1 className="title">FAQ</h1>
                  <h2 className="subtitle is-4">Lorum ipsum and all of that jazz.</h2>

                  <div className="columns">
                    {this.state.faqs.map(faq =>
                      <div className="column is-one-third">
                        <div className="card">
                        <div className="card-content">
                          <p className="title">{ faq.title }</p>
                          <p className="answer">{ faq.body }</p>
                        </div>
                        </div>
                      </div>
                    )}
                  </div>
                </section>
              </div>
            </div>
        );
    }
}

export default Faq;

// compare-angular/src/app/faq/faq.component.ts
import { Component, OnInit } from '@angular/core';
import { Http } from '@angular/http';
import 'rxjs/add/operator/map';

@Component({
  selector: 'app-faq',
  templateUrl: './faq.component.html',
  styleUrls: ['./faq.component.sass']
})
export class FaqComponent implements OnInit {

  faqs: Array<any>;

  constructor(private http:Http) {
    this.http.get('https://jsonplaceholder.typicode.com/posts')
      .map(response => response.json())
      .subscribe(res => this.faqs = res);
   }

  ngOnInit() {
  }

}

<div class="container">
  <section class="section">
    <h1 class="title">FAQ</h1>
    <h2 class="subtitle is-4">Lorum ipsum and all of that jazz.</h2>

    <div class="columns">
      <div class="column is-one-third" *ngFor="let faq of (faqs ? faqs.slice(0, 10): [])">
        <div class="card">
          <div class="card-content">
            <p class="title">{{ faq.title }}</p>
            <p class="answer">{{ faq.body }}</p>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>
